agent:
  system_template: |
    You are a helpful assistant that can interact with a computer.

    Your response must contain exactly ONE bash code block with ONE command (or commands connected with && or ||).
    Include a THOUGHT section before your command where you explain your reasoning process.
    Format your response as shown in <format_example>.

    <format_example>
    Your reasoning and analysis here. Explain why you want to perform the action.

    ```bash
    your_command_here
    ```
    </format_example>

    Failure to follow these rules will cause your response to be rejected.
  system_template_abstract: |
    You are a project manager. You are responsible for task decomposition.
  instance_template: |
    Please solve this issue: {{task}}

    You can execute bash commands and edit files to implement the necessary changes.

    ## Important Rules

    1. Every response must contain exactly one action
    2. The action must be enclosed in triple backticks
    3. Directory or environment variable changes are not persistent. Every action is executed in a new subshell.
       However, you can prefix any action with `MY_ENV_VAR=MY_VALUE cd /path/to/working/dir && ...` or write/load environment variables from files

    <system_information>
    {{system}} {{release}} {{version}} {{machine}}
    </system_information>

    ```
  instance_template_abstract: |
    Your task is: {{task}}
    You can delegate the following subtasks:
    {% for tool in tools %}
    name={{tool.name}}, description={{tool.description}}
    {% endfor %}
  action_observation_template: |
    <returncode>{{output.returncode}}</returncode>
    {% if output.output | length < 10000 -%}
    <output>
    {{ output.output -}}
    </output>
    {%- else -%}
    <warning>
    The output of your last command was too long.
    Please try a different command that produces less output.
    If you're looking at a file you can try use head, tail or sed to view a smaller number of lines selectively.
    If you're using grep or find and it produced too much output, you can use a more selective search pattern.
    If you really need to see something from the full command's output, you can redirect output to a file and then search in that file.
    </warning>
    {%- set elided_chars = output.output | length - 10000 -%}
    <output_head>
    {{ output.output[:5000] }}
    </output_head>
    <elided_chars>
    {{ elided_chars }} characters elided
    </elided_chars>
    <output_tail>
    {{ output.output[-5000:] }}
    </output_tail>
    {%- endif -%}
  format_error_template: |
    Please always provide EXACTLY ONE action in triple backticks, found {{actions|length}} actions.
    If you want to end the task, please issue the following command: `echo COMPLETE_TASK_AND_SUBMIT_FINAL_OUTPUT`
    without any other command.
    Else, please format your response exactly as follows:

    <response_example>
    Here are some thoughts about why you want to perform the action.

    ```bash
    <action>
    ```
    </response_example>

    Note: In rare cases, if you need to reference a similar format in your command, you might have
    to proceed in two steps, first writing TRIPLEBACKTICKSBASH, then replacing them with ```bash.
  timeout_template: |
    The last command <command>{{action['action']}}</command> timed out and has been killed.
    The output of the command was:
    {% if output | length < 10000 -%}
    <output>
    {{output}}
    </output>
    {%- else -%}
    <warning>Output was too long and has been truncated.</warning>
    <output_head>
    {{ output[:5000] }}
    </output_head>
    <elided_chars>{{ output | length - 10000 }} characters elided</elided_chars>
    <output_tail>
    {{ output[-5000:] }}
    </output_tail>
    {%- endif %}
    Please try another command and make sure to avoid those requiring interactive input.
  tool_template: |

    ## Allowed list of bash commands:
    {% for tool in tools %}
    Use `{{ tool.name }}` to {{ tool.description }}
    {% endfor %}
 
    Do not use other bash tools!
 
    ## Useful command examples
    
    {%- for tool in tools -%}
    {%- if 'prompt_instruction' in tool -%}
    ```bash
    {{ tool.prompt_instruction }}
    {%- endif -%}
    {%- endfor -%}
   

    Format your response as shown in <format_example>.

    <format_example>
    Your reasoning and analysis here. Explain why you want to perform the action.

    ```bash
    your_command_here
    ```
    </format_example>

    Failure to follow these rules will cause your response to be rejected.

    To accomplish the next step, follow the instruction: {{explantion}}.
  next_direction_template: |
    Your task is to analyse project progress below and to propose the next step direction from the following list:
    {% for tool in tools %}
    name={{tool.name}}, description={{tool.description}}
    {% endfor %}

    In the response provide only one  block "<thinking/>". The response example is:

    <thinking>
    Explain here you decision
    </thinking>

    Respond only these two blocks!
  step_limit: 0.
  cost_limit: 0.
  tools:
    - name: echo
      description: General purpose bash command
    - name: grep
      description: Search for a specific pattern or word inside files
    - name: ls
      description: List files and directories in the current folder
    - name: cd
      description: Change the current working directory
    - name: cat
      description: Read the content of the file
    - name: find
      description: Directory search and file locating capabilities
    - name: nl
      description: View the contents of a file with numbered lines
      prompt_instruction: |
        # View specific lines with numbers
        nl -ba filename.py | sed -n '10,20p'
    - name: sed
      description: Edit files by replace
      prompt_instruction: |
        # Replace all occurrences
        sed -i 's/old_string/new_string/g' filename.py

        # Replace only first occurrence
        sed -i 's/old_string/new_string/' filename.py

        # Replace first occurrence on line 1
        sed -i '1s/old_string/new_string/' filename.py

        # Replace all occurrences in lines 1-10
        sed -i '1,10s/old_string/new_string/g' filename.py
environment:
  env:
    PAGER: cat
    MANPAGER: cat
    LESS: -R
    PIP_PROGRESS_BAR: 'off'
    TQDM_DISABLE: '1'
model:
  model_name: "glm-4.7"
  cost_tracking: "ignore_errors"
  model_kwargs:
    custom_llm_provider: "openai"
    api_base: "https://api.z.ai/api/coding/paas/v4"
    api_key: "6909c1698fe74f8e89781b64d08a702d.uH5MocsDSGmFuY4o"
